"""contest dates to datetime + timezone

Revision ID: 1a0023d3a504
Revises: d2818b636157
Create Date: 2026-08-16 09:28:16.455459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0023d3a504'
down_revision = 'd2818b636157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        # server_default backfills existing rows (column is NOT NULL); new rows
        # without an explicit zone also default to UTC at the DB level.
        batch_op.add_column(sa.Column('timezone', sa.String(length=64),
                                      nullable=False, server_default='UTC'))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # Pre-existing end dates were plain dates (interpreted at 00:00). Under the
    # new inclusive-instant semantics that would end the contest at the *start*
    # of the end day; bump to 23:59:59 of the same day (UTC) so the end day stays
    # included, matching how new contests are created.
    op.execute(
        "UPDATE contests "
        "SET end_date = TIMESTAMP(DATE(end_date), '23:59:59') "
        "WHERE end_date IS NOT NULL"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
