"""Make reason field optional for auto-approved requests

Revision ID: 25066b6f7958
Revises: 857e1e712b40
Create Date: 2026-08-03 01:43:23.775309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25066b6f7958'
down_revision = '857e1e712b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest_requests', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest_requests', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
